# Generated by Django 5.0.3 on 2024-05-21 08:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseDesc', models.CharField(max_length=200)),
                ('courseDetails', tinymce.models.HTMLField()),
                ('courseImg', models.FileField(default=None, max_length=250, null=True, upload_to='course/')),
            ],
        ),
    ]
